=== horstoeko/docugen/src/assets/configschema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "title",
        "description",
        "codesnippets",
        "texts",
        "documentations",
        "outputs"
    ],
    "properties": {
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "codesnippets": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                    "id",
                    "lines"
                ],
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "title": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "lines": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "texts": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                    "id",
                    "lines"
                ],
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "title": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "lines": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "blocks": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                    "id",
                    "lines"
                ],
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "title": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string",
                        "oneOf": [
                            {
                                "const": "comment"
                            },
                            {
                                "const": "code"
                            },
                            {
                                "const": "blank"
                            }
                        ]
                    },
                    "language": {
                        "type": "string"
                    },
                    "lines": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "options": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "id",
                                "value"
                            ],
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "value": {
                                    "type": ["string", "integer", "boolean", "array"]
                                }
                            }
                        }
                    },
                    "visibleexpression": {
                        "type": "string"
                    }
                }
            }
        },
        "documentations": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                    "id",
                    "title",
                    "description",
                    "blocks"
                ],
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "title": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "blocks": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "options": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "id",
                                "value"
                            ],
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "value": {
                                    "type": ["string", "integer", "boolean", "array"]
                                }
                            }
                        }
                    }
                }
            }
        },
        "outputs": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                    "id",
                    "outputtype",
                    "documentationid"
                ],
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "title": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "outputtype": {
                        "type": "string",
                        "oneOf": [
                            {
                                "const": "php"
                            },
                            {
                                "const": "markdown"
                            },
                            {
                                "const": "html"
                            },
                            {
                                "const": "custom"
                            }
                        ]
                    },
                    "documentationid": {
                        "type": "string"
                    },
                    "filepath": {
                        "type": "string"
                    },
                    "filename": {
                        "type": "string"
                    },
                    "filepathisabsolute": {
                        "type": "boolean"
                    },
                    "titlemode": {
                        "type": "integer",
                        "oneOf": [
                            {
                                "const": 0
                            },
                            {
                                "const": 1
                            },
                            {
                                "const": 2
                            }
                        ]
                    },
                    "descriptionmode": {
                        "type": "integer",
                        "oneOf": [
                            {
                                "const": 0
                            },
                            {
                                "const": 1
                            },
                            {
                                "const": 2
                            }
                        ]
                    },
                    "outputdestination": {
                        "type": "integer",
                        "oneOf": [
                            {
                                "const": 0
                            },
                            {
                                "const": 1
                            }
                        ]
                    },
                    "options": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "id",
                                "value"
                            ],
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "value": {
                                    "type": ["string", "integer", "boolean", "array"]
                                }
                            }
                        }
                    }
                },
                "allOf": [
                    {
                        "if": {
                            "properties": {
                                "outputdestination": {
                                    "const": 0
                                }
                            }
                        },
                        "then": {
                            "required": [
                                "filepath",
                                "filename"
                            ]
                        }
                    }
                ]
            }
        }
    }
}

=== horstoeko/docugen/examples/config2.json
{
    "title": "Sample Project",
    "description": "This is a sample project",
    "codesnippets": [
        {
            "id": "CS_ZF_USE_BUILDER",
            "lines": [
                "use horstoeko\\zugferd\\codelists\\ZugferdCountryCodes;",
                "use horstoeko\\zugferd\\codelists\\ZugferdCurrencyCodes;",
                "use horstoeko\\zugferd\\codelists\\ZugferdElectronicAddressScheme;",
                "use horstoeko\\zugferd\\codelists\\ZugferdInvoiceType;",
                "use horstoeko\\zugferd\\codelists\\ZugferdReferenceCodeQualifiers;",
                "use horstoeko\\zugferd\\codelists\\ZugferdUnitCodes;",
                "use horstoeko\\zugferd\\codelists\\ZugferdVatCategoryCodes;",
                "use horstoeko\\zugferd\\codelists\\ZugferdVatTypeCodes;",
                "use horstoeko\\zugferd\\ZugferdDocumentBuilder;",
                "use horstoeko\\zugferd\\ZugferdProfiles;"
            ]
        },
        {
            "id": "CS_ZF_AUTOLOAD",
            "lines": [
                "require __DIR__ . \"/../vendor/autoload.php\";"
            ]
        },
        {
            "id": "CS_ZF_EXAMPLEHELPER",
            "lines": [
                "require __DIR__ . \"/00_ExampleHelpers.php\";"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_INSTANCIATE_EN16931",
            "lines": [
                "$documentBuilder = ZugferdDocumentBuilder::createNew(ZugferdProfiles::PROFILE_EN16931);"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_INSTANCIATE_XRECHNUNG",
            "lines": [
                "$documentBuilder = ZugferdDocumentBuilder::createNew(ZugferdProfiles::PROFILE_XRECHNUNG_3);"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_SET_GENERAL_INVOICE_INFORMATION",
            "lines": [
                "$documentBuilder->setDocumentInformation(",
                "  'R-2024/00001',                                     // @TXTPART:TXTPART_DOCUMENT:2 number (BT-1)",
                "  ZugferdInvoiceType::INVOICE,                        // Type \"@TXTPART:TXTPART_DOCUMENT:2\" (BT-3)",
                "  DateTime::createFromFormat('Ymd', '20241231'),      // @TXTPART:TXTPART_DOCUMENT:2 fate (BT-2)",
                "  ZugferdCurrencyCodes::EURO                          // @TXTPART:TXTPART_DOCUMENT:2 currency is EUR (Euro) (BT-5)",
                ");"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_ADD_DOCUMENT_NOTE",
            "lines": [
                "$documentBuilder->addDocumentNote('Lieferant GmbH' . PHP_EOL . 'Lieferantenstraße 20' . PHP_EOL . '80333 München' . PHP_EOL . 'Deutschland' . PHP_EOL . 'Geschäftsführer: Hans Muster' . PHP_EOL . 'Handelsregisternummer: H A 123' . PHP_EOL . PHP_EOL, null, 'REG');"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_SET_DOCUMENT_BILLING_PERIOD",
            "lines": [
                "$documentBuilder->setDocumentBillingPeriod(DateTime::createFromFormat('Ymd', '20250101'), DateTime::createFromFormat('Ymd', '20250131'), '01.01.2025 - 31.01.2025');"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_ADD_DOCUMENTS_SUPPORTING_THE_INVOICE",
            "lines": [
                "$documentBuilder->addDocumentInvoiceSupportingDocumentWithUri('REFDOC-2024/00001-1', 'http.//some.url', 'Inhaltsstoffe Joghurt');",
                "$documentBuilder->addDocumentInvoiceSupportingDocumentWithFile('REFDOC-2024/00001-2', __DIR__ . '/assets/00_AdditionalDocument.csv', 'Herkunftsnachweis Trennblätter');"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_ADD_TENDER_OR_LOT_REFERENCE",
            "lines": [
                "$documentBuilder->addDocumentTenderOrLotReferenceDocument('LOS 738625');"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_ADD_DETAILS_OF_INVOICED_OBJECT",
            "lines": [
                "$documentBuilder->addDocumentInvoicedObjectReferenceDocument('125', ZugferdReferenceCodeQualifiers::SALE_PERS_NUMB); // Sales person number"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_SET_CONTRACT_REFERENCE",
            "lines": [
                "$documentBuilder->setDocumentContractReferencedDocument('CON-2024/2025-001');"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_SET_PROJECT_REFERENCE",
            "lines": [
                "$documentBuilder->setDocumentProcuringProject('PROJ-2025-001-1', 'Allgemeine Dienstleistungen');"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_ADD_PAYMENTMEAN",
            "lines": [
                "$documentBuilder->addDocumentPaymentMeanToDirectDebit('DE12500105170648489890', 'R-2024/00001');"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_ADD_PAYMENTTERM",
            "lines": [
                "$documentBuilder->addDocumentPaymentTerm('Wird von Konto DE12500105170648489890 abgebucht', DateTime::createFromFormat('Ymd', '20250131'), 'MANDATE-2024/000001');"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_SET_SELLER",
            "lines": [
                "$documentBuilder->setDocumentSeller('Lieferant GmbH', '549910');",
                "$documentBuilder->addDocumentSellerGlobalId('4000001123452', '0088');",
                "$documentBuilder->addDocumentSellerTaxNumber('201/113/40209');",
                "$documentBuilder->addDocumentSellerVATRegistrationNumber('DE123456789');",
                "$documentBuilder->setDocumentSellerAddress('Lieferantenstraße 20', '', '', '80333', 'München', ZugferdCountryCodes::GERMANY);",
                "$documentBuilder->setDocumentSellerContact('H. Müller', 'Verkauf', '+49-111-2222222', '+49-111-3333333', 'hm@lieferant.de');",
                "$documentBuilder->setDocumentSellerCommunication(ZugferdElectronicAddressScheme::UNECE3155_EM, 'sales@lieferant.de');"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_SET_BUYER",
            "lines": [
                "$documentBuilder->setDocumentBuyer('Kunden AG Mitte', 'GE2020211');",
                "$documentBuilder->setDocumentBuyerAddress('Kundenstraße 15', '', '', '69876', 'Frankfurt', ZugferdCountryCodes::GERMANY);",
                "$documentBuilder->setDocumentBuyerContact('H. Meier', 'Einkauf', '+49-333-4444444', '+49-333-5555555', 'hm@kunde.de');",
                "$documentBuilder->setDocumentBuyerCommunication(ZugferdElectronicAddressScheme::UNECE3155_EM, 'purchase@kunde.de');"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_SET_PAYEE",
            "lines": [
                "$documentBuilder->setDocumentPayee('Kunden AG Zahlungsdienstleistung');"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_SET_BUYER_ORDER_REFERENCE",
            "lines": [
                "$documentBuilder->setDocumentBuyerOrderReferencedDocument('PO-2024-0003324');"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_SET_SELLER_ORDER_REFERENCE",
            "lines": [
                "$documentBuilder->setDocumentSellerOrderReferencedDocument('SO-2024-000993337');"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_SET_SHIP_TO",
            "lines": [
                "$documentBuilder->setDocumentShipTo('Kunden AG Ost');",
                "$documentBuilder->setDocumentShipToAddress('Lieferstraße 1', '', '', '04109', 'Leipzig', ZugferdCountryCodes::GERMANY);"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_SET_DELIVERY_DATE",
            "lines": [
                "$documentBuilder->setDocumentSupplyChainEvent(DateTime::createFromFormat('Ymd', '20250115'));"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_ADD_POSITION_1",
            "lines": [
                "$documentBuilder->addNewPosition('1');",
                "$documentBuilder->setDocumentPositionProductDetails('Trennblätter A4', '50er Pack', 'TB100A4');",
                "$documentBuilder->setDocumentPositionNetPrice(9.9000);",
                "$documentBuilder->setDocumentPositionQuantity(20, ZugferdUnitCodes::REC20_PIECE);",
                "$documentBuilder->addDocumentPositionTax(ZugferdVatCategoryCodes::STAN_RATE, ZugferdVatTypeCodes::VALUE_ADDED_TAX, 19);",
                "$documentBuilder->setDocumentPositionLineSummation(198.0);"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_ADD_POSITION_2",
            "lines": [
                "$documentBuilder->addNewPosition('2');",
                "$documentBuilder->setDocumentPositionProductDetails('Joghurt Banane', 'B-Ware', 'ARNR2');",
                "$documentBuilder->setDocumentPositionNetPrice(5.5000);",
                "$documentBuilder->setDocumentPositionQuantity(50, ZugferdUnitCodes::REC20_PIECE);",
                "$documentBuilder->addDocumentPositionTax(ZugferdVatCategoryCodes::STAN_RATE, ZugferdVatTypeCodes::VALUE_ADDED_TAX, 7);",
                "$documentBuilder->setDocumentPositionLineSummation(275.0);"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_ADD_POSITION_3",
            "lines": [
                "$documentBuilder->addNewPosition('3');",
                "$documentBuilder->setDocumentPositionProductDetails('Joghurt Erdbeer', '', 'ARNR3');",
                "$documentBuilder->setDocumentPositionNetPrice(4.0000);",
                "$documentBuilder->setDocumentPositionQuantity(100, ZugferdUnitCodes::REC20_PIECE);",
                "$documentBuilder->addDocumentPositionTax(ZugferdVatCategoryCodes::STAN_RATE, ZugferdVatTypeCodes::VALUE_ADDED_TAX, 7);",
                "$documentBuilder->setDocumentPositionLineSummation(400.0);"
            ]
        },
        {
            "id": "CS_ZF_BUILDER_ADD_VAT_BREAKDOWN",
            "lines": [
